# frozen_string_literal: true

source "https://rubygems.org"

gem "aws-sdk-s3"
gem "falcon"
gem "ox"
gem "sentry-ruby"
gem "sinatra"
gem "zeitwerk"

group :development, :test do
  gem "async-rspec"
  gem "rspec"
  gem "simplecov"
end

group :development do
  gem "rubocop"
  gem "rubocop-performance"
  gem "rubocop-rspec"
end
