AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-performance
  - rubocop-rspec

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

RSpec/ExampleLength:
  Max: 10