name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | \
            docker login ghcr.io --username ${{ steps.get_repo_owner.outputs.repo_owner }} --password-stdin

      - name: Build functions
        run: |
          curl -sSL https://cli.openfaas.com | sh
          faas-cli build
          faas-cli push
