name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2

      - name: Build and publish to ghcr.io
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository_owner }}/fn-hass-listener
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "hass-listener/Dockerfile"
          image_tag: "latest"
          context: hass-listener
