name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2

      - name: OpenFaaS build and push
        uses: mrsimpson/action-openfaas-build@master
        with:
          stack-file: stack.yml
          platforms: linux/amd64
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.GITHUB_TOKEN }}
