name: Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        function:
          - hass-listener
          - backup-stats-collector

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.function }}/function/Gemfile

    steps:
      - uses: actions/checkout@v2

      - uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Europe/Berlin"

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run linter
        run: |
          cd ${{ github.workspace }}/${{ matrix.function }}/function
          bundle exec rubocop

      - name: Run tests
        run: |
          cd ${{ github.workspace }}/${{ matrix.function }}/function
          bundle exec rspec

      - name: Build and publish to ghcr.io
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository_owner }}/fn-${{ matrix.function }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: "${{ matrix.function }}/Dockerfile"
          image_tag: latest
          context: ${{ matrix.function }}

      # TODO: deploy
